// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.
// Demo M=4 T=4: full-tile parallel LOAD/STORE; A=I, B=1..16 → C=B
// @vs view matrix C array=c rows=4 cols=4
module gemm4_tiled_demo (
  input  wire clk,
  input  wire rst,
  output wire done,
  output wire [3:0] phase,
  output wire [31:0] c [0:3][0:3]
);
  reg start, kicked;
  wire host_we, host_re;
  wire [7:0] ti, tj, tk;
  reg  [7:0]  a_full [0:3][0:3];
  reg  [7:0]  b_full [0:3][0:3];
  reg  [7:0]  host_a [0:3][0:3];
  reg  [7:0]  host_b [0:3][0:3];
  wire [31:0] host_c [0:3][0:3];
  wire [7:0]  a_mem [0:3][0:3];
  wire [7:0]  b_mem [0:3][0:3];
  wire [31:0] c_comb [0:3][0:3];
  reg  [31:0] c_full [0:3][0:3];
  integer ri, cj, ii, jj;

  gemm4_mac_array u_mac (.a(a_mem), .b(b_mem), .c(c_comb));

  gemm4_tiled_ctrl u_ctrl (
    .clk(clk), .rst(rst), .start(start),
    .host_we(host_we), .host_a(host_a), .host_b(host_b),
    .host_re(host_re), .host_c(host_c),
    .done(done), .phase(phase), .ti(ti), .tj(tj), .tk(tk),
    .a_mem(a_mem), .b_mem(b_mem), .c_comb(c_comb)
  );

  assign host_we = (phase == 4'd2);
  assign host_re = (phase == 4'd6);

  assign c[0][0] = c_full[0][0];
  assign c[0][1] = c_full[0][1];
  assign c[0][2] = c_full[0][2];
  assign c[0][3] = c_full[0][3];
  assign c[1][0] = c_full[1][0];
  assign c[1][1] = c_full[1][1];
  assign c[1][2] = c_full[1][2];
  assign c[1][3] = c_full[1][3];
  assign c[2][0] = c_full[2][0];
  assign c[2][1] = c_full[2][1];
  assign c[2][2] = c_full[2][2];
  assign c[2][3] = c_full[2][3];
  assign c[3][0] = c_full[3][0];
  assign c[3][1] = c_full[3][1];
  assign c[3][2] = c_full[3][2];
  assign c[3][3] = c_full[3][3];

  // Parallel tile extract from full A/B (T² reads each beat)
  always @* begin
    for (ii = 0; ii < 4; ii = ii + 1)
      for (jj = 0; jj < 4; jj = jj + 1) begin
        host_a[ii][jj] = a_full[ti * 4 + ii][tk * 4 + jj];
        host_b[ii][jj] = b_full[tk * 4 + ii][tj * 4 + jj];
      end
  end

  initial begin
    for (ri = 0; ri < 4; ri = ri + 1)
      for (cj = 0; cj < 4; cj = cj + 1) begin
        if (ri == cj) a_full[ri][cj] = 8'd1;
        else          a_full[ri][cj] = 8'd0;
        b_full[ri][cj] = ri * 4 + cj + 1;
      end
  end

  always @(posedge clk) begin
    if (rst) begin
      start <= 1'b0; kicked <= 1'b0;
      for (ri = 0; ri < 4; ri = ri + 1)
        for (cj = 0; cj < 4; cj = cj + 1)
          c_full[ri][cj] <= 32'd0;
    end else begin
      start <= 1'b0;
      if (!kicked) begin start <= 1'b1; kicked <= 1'b1; end
      // 1 beat: parallel write-back of whole C tile
      if (phase == 4'd6) begin
        for (ii = 0; ii < 4; ii = ii + 1)
          for (jj = 0; jj < 4; jj = jj + 1)
            c_full[ti * 4 + ii][tj * 4 + jj] <= host_c[ii][jj];
      end
    end
  end
endmodule
