// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.
module gemm1024_tiled_top (
  input  wire clk,
  input  wire rst,
  input  wire start,
  input  wire          host_we,
  input  wire [7:0]    host_a [0:31][0:31],
  input  wire [7:0]    host_b [0:31][0:31],
  input  wire          host_re,
  output wire [31:0]   host_c [0:31][0:31],
  output wire          done,
  output wire [3:0]    phase,
  output wire [7:0]    ti,
  output wire [7:0]    tj,
  output wire [7:0]    tk
);
  wire [7:0]  a_mem [0:31][0:31];
  wire [7:0]  b_mem [0:31][0:31];
  wire [31:0] c_comb [0:31][0:31];

  gemm32_mac_array u_mac (.a(a_mem), .b(b_mem), .c(c_comb));

  gemm1024_tiled_ctrl u_ctrl (
    .clk(clk), .rst(rst), .start(start),
    .host_we(host_we), .host_a(host_a), .host_b(host_b),
    .host_re(host_re), .host_c(host_c),
    .done(done), .phase(phase), .ti(ti), .tj(tj), .tk(tk),
    .a_mem(a_mem), .b_mem(b_mem), .c_comb(c_comb)
  );
endmodule
