// Auto-generated by tools/fpga_gemm3/gen_mac_array.py — do not edit by hand.
// Fixed multiplier cluster: C = A·B, N=2
//   8 multipliers + 4 N-input sums; pure combo; 1 cycle latch outside.
//
// @vs view matrix A array=a rows=2 cols=2
// @vs view matrix B array=b rows=2 cols=2
// @vs view matrix C array=c rows=2 cols=2
// @vs op matmul out=C left=A right=B
module gemm2_mac_array (
  input  wire [7:0] a [0:1][0:1],
  input  wire [7:0] b [0:1][0:1],
  output wire [31:0] c [0:1][0:1]
);
  // ---- 8 multipliers: mul_i_j_k = A[i][k] * B[k][j] ----
  wire [31:0] mul_0_0_0;
  assign mul_0_0_0 = a[0][0] * b[0][0];
  wire [31:0] mul_0_0_1;
  assign mul_0_0_1 = a[0][1] * b[1][0];
  wire [31:0] mul_0_1_0;
  assign mul_0_1_0 = a[0][0] * b[0][1];
  wire [31:0] mul_0_1_1;
  assign mul_0_1_1 = a[0][1] * b[1][1];
  wire [31:0] mul_1_0_0;
  assign mul_1_0_0 = a[1][0] * b[0][0];
  wire [31:0] mul_1_0_1;
  assign mul_1_0_1 = a[1][1] * b[1][0];
  wire [31:0] mul_1_1_0;
  assign mul_1_1_0 = a[1][0] * b[0][1];
  wire [31:0] mul_1_1_1;
  assign mul_1_1_1 = a[1][1] * b[1][1];
  // ---- 4 reductions: C[i][j] = Σ_k mul_i_j_k ----
  assign c[0][0] = mul_0_0_0 + mul_0_0_1;
  assign c[0][1] = mul_0_1_0 + mul_0_1_1;
  assign c[1][0] = mul_1_0_0 + mul_1_0_1;
  assign c[1][1] = mul_1_1_0 + mul_1_1_1;
endmodule
