// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.
// Tiled GEMM (full-tile parallel bus): M=4, T=4, NT=1, leaves=1
// LOAD=1 beat (parallel A||B), STORE=1 beat (parallel C). Leaf mac still 1-cycle latch.
module gemm4_tiled_ctrl (
  input  wire clk,
  input  wire rst,
  input  wire start,
  input  wire          host_we,
  input  wire [7:0]    host_a [0:3][0:3],
  input  wire [7:0]    host_b [0:3][0:3],
  input  wire          host_re,
  output reg  [31:0]   host_c [0:3][0:3],
  output reg           done,
  output reg  [3:0]    phase,
  output reg  [7:0]    ti,
  output reg  [7:0]    tj,
  output reg  [7:0]    tk,
  output reg  [7:0]    a_mem [0:3][0:3],
  output reg  [7:0]    b_mem [0:3][0:3],
  input  wire [31:0]   c_comb [0:3][0:3]
);
  reg [31:0] prod [0:3][0:3];
  reg [31:0] acc [0:3][0:3];
  integer ii, jj;
  reg started;

  // 0 IDLE 1 CLEAR 2 LOAD 3 LATCH 4 ACCUM 5 ADV 6 STORE 7 FIN
  always @(posedge clk) begin
    if (rst) begin
      done <= 1'b0; phase <= 4'd0; started <= 1'b0;
      ti <= 8'd0; tj <= 8'd0; tk <= 8'd0;
      for (ii = 0; ii < 4; ii = ii + 1)
        for (jj = 0; jj < 4; jj = jj + 1) begin
          a_mem[ii][jj] <= 8'd0; b_mem[ii][jj] <= 8'd0;
          prod[ii][jj] <= 32'd0; acc[ii][jj] <= 32'd0;
          host_c[ii][jj] <= 32'd0;
        end
    end else if (phase == 4'd0) begin
      if (start && !started) begin
        done <= 1'b0; started <= 1'b1;
        ti <= 8'd0; tj <= 8'd0; tk <= 8'd0;
        phase <= 4'd1;
      end
    end else if (phase == 4'd1) begin
      for (ii = 0; ii < 4; ii = ii + 1)
        for (jj = 0; jj < 4; jj = jj + 1)
          acc[ii][jj] <= 32'd0;
      phase <= 4'd2;
    end else if (phase == 4'd2) begin
      // 1 beat: parallel write entire A and B tiles (2·T² ports)
      if (host_we) begin
        for (ii = 0; ii < 4; ii = ii + 1)
          for (jj = 0; jj < 4; jj = jj + 1) begin
            a_mem[ii][jj] <= host_a[ii][jj];
            b_mem[ii][jj] <= host_b[ii][jj];
          end
      end
      phase <= 4'd3;
    end else if (phase == 4'd3) begin
      for (ii = 0; ii < 4; ii = ii + 1)
        for (jj = 0; jj < 4; jj = jj + 1)
          prod[ii][jj] <= c_comb[ii][jj];
      phase <= 4'd4;
    end else if (phase == 4'd4) begin
      for (ii = 0; ii < 4; ii = ii + 1)
        for (jj = 0; jj < 4; jj = jj + 1)
          acc[ii][jj] <= acc[ii][jj] + prod[ii][jj];
      phase <= 4'd5;
    end else if (phase == 4'd5) begin
      if (tk + 8'd1 >= 8'd1) begin
        for (ii = 0; ii < 4; ii = ii + 1)
          for (jj = 0; jj < 4; jj = jj + 1)
            host_c[ii][jj] <= acc[ii][jj];
        phase <= 4'd6;
      end else begin
        tk <= tk + 8'd1;
        phase <= 4'd2;
      end
    end else if (phase == 4'd6) begin
      // 1 beat: host samples parallel host_c
      if (host_re) begin
        tk <= 8'd0;
        if (tj + 8'd1 >= 8'd1) begin
          if (ti + 8'd1 >= 8'd1) phase <= 4'd7;
          else begin ti <= ti + 8'd1; tj <= 8'd0; phase <= 4'd1; end
        end else begin
          tj <= tj + 8'd1; phase <= 4'd1;
        end
      end
    end else if (phase == 4'd7) begin
      done <= 1'b1; started <= 1'b0; phase <= 4'd0;
    end
  end
endmodule
