// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.
// Demo M=8 T=4: full-tile parallel LOAD/STORE; A=I, B=1..64 → C=B
// @vs view matrix C array=c rows=8 cols=8
module gemm8_tiled_demo (
  input  wire clk,
  input  wire rst,
  output wire done,
  output wire [3:0] phase,
  output wire [31:0] c [0:7][0:7]
);
  reg start, kicked;
  wire host_we, host_re;
  wire [7:0] ti, tj, tk;
  reg  [7:0]  a_full [0:7][0:7];
  reg  [7:0]  b_full [0:7][0:7];
  reg  [7:0]  host_a [0:3][0:3];
  reg  [7:0]  host_b [0:3][0:3];
  wire [31:0] host_c [0:3][0:3];
  wire [7:0]  a_mem [0:3][0:3];
  wire [7:0]  b_mem [0:3][0:3];
  wire [31:0] c_comb [0:3][0:3];
  reg  [31:0] c_full [0:7][0:7];
  integer ri, cj, ii, jj;

  gemm4_mac_array u_mac (.a(a_mem), .b(b_mem), .c(c_comb));

  gemm8_tiled_ctrl u_ctrl (
    .clk(clk), .rst(rst), .start(start),
    .host_we(host_we), .host_a(host_a), .host_b(host_b),
    .host_re(host_re), .host_c(host_c),
    .done(done), .phase(phase), .ti(ti), .tj(tj), .tk(tk),
    .a_mem(a_mem), .b_mem(b_mem), .c_comb(c_comb)
  );

  assign host_we = (phase == 4'd2);
  assign host_re = (phase == 4'd6);

  assign c[0][0] = c_full[0][0];
  assign c[0][1] = c_full[0][1];
  assign c[0][2] = c_full[0][2];
  assign c[0][3] = c_full[0][3];
  assign c[0][4] = c_full[0][4];
  assign c[0][5] = c_full[0][5];
  assign c[0][6] = c_full[0][6];
  assign c[0][7] = c_full[0][7];
  assign c[1][0] = c_full[1][0];
  assign c[1][1] = c_full[1][1];
  assign c[1][2] = c_full[1][2];
  assign c[1][3] = c_full[1][3];
  assign c[1][4] = c_full[1][4];
  assign c[1][5] = c_full[1][5];
  assign c[1][6] = c_full[1][6];
  assign c[1][7] = c_full[1][7];
  assign c[2][0] = c_full[2][0];
  assign c[2][1] = c_full[2][1];
  assign c[2][2] = c_full[2][2];
  assign c[2][3] = c_full[2][3];
  assign c[2][4] = c_full[2][4];
  assign c[2][5] = c_full[2][5];
  assign c[2][6] = c_full[2][6];
  assign c[2][7] = c_full[2][7];
  assign c[3][0] = c_full[3][0];
  assign c[3][1] = c_full[3][1];
  assign c[3][2] = c_full[3][2];
  assign c[3][3] = c_full[3][3];
  assign c[3][4] = c_full[3][4];
  assign c[3][5] = c_full[3][5];
  assign c[3][6] = c_full[3][6];
  assign c[3][7] = c_full[3][7];
  assign c[4][0] = c_full[4][0];
  assign c[4][1] = c_full[4][1];
  assign c[4][2] = c_full[4][2];
  assign c[4][3] = c_full[4][3];
  assign c[4][4] = c_full[4][4];
  assign c[4][5] = c_full[4][5];
  assign c[4][6] = c_full[4][6];
  assign c[4][7] = c_full[4][7];
  assign c[5][0] = c_full[5][0];
  assign c[5][1] = c_full[5][1];
  assign c[5][2] = c_full[5][2];
  assign c[5][3] = c_full[5][3];
  assign c[5][4] = c_full[5][4];
  assign c[5][5] = c_full[5][5];
  assign c[5][6] = c_full[5][6];
  assign c[5][7] = c_full[5][7];
  assign c[6][0] = c_full[6][0];
  assign c[6][1] = c_full[6][1];
  assign c[6][2] = c_full[6][2];
  assign c[6][3] = c_full[6][3];
  assign c[6][4] = c_full[6][4];
  assign c[6][5] = c_full[6][5];
  assign c[6][6] = c_full[6][6];
  assign c[6][7] = c_full[6][7];
  assign c[7][0] = c_full[7][0];
  assign c[7][1] = c_full[7][1];
  assign c[7][2] = c_full[7][2];
  assign c[7][3] = c_full[7][3];
  assign c[7][4] = c_full[7][4];
  assign c[7][5] = c_full[7][5];
  assign c[7][6] = c_full[7][6];
  assign c[7][7] = c_full[7][7];

  // Parallel tile extract from full A/B (T² reads each beat)
  always @* begin
    for (ii = 0; ii < 4; ii = ii + 1)
      for (jj = 0; jj < 4; jj = jj + 1) begin
        host_a[ii][jj] = a_full[ti * 4 + ii][tk * 4 + jj];
        host_b[ii][jj] = b_full[tk * 4 + ii][tj * 4 + jj];
      end
  end

  initial begin
    for (ri = 0; ri < 8; ri = ri + 1)
      for (cj = 0; cj < 8; cj = cj + 1) begin
        if (ri == cj) a_full[ri][cj] = 8'd1;
        else          a_full[ri][cj] = 8'd0;
        b_full[ri][cj] = ri * 8 + cj + 1;
      end
  end

  always @(posedge clk) begin
    if (rst) begin
      start <= 1'b0; kicked <= 1'b0;
      for (ri = 0; ri < 8; ri = ri + 1)
        for (cj = 0; cj < 8; cj = cj + 1)
          c_full[ri][cj] <= 32'd0;
    end else begin
      start <= 1'b0;
      if (!kicked) begin start <= 1'b1; kicked <= 1'b1; end
      // 1 beat: parallel write-back of whole C tile
      if (phase == 4'd6) begin
        for (ii = 0; ii < 4; ii = ii + 1)
          for (jj = 0; jj < 4; jj = jj + 1)
            c_full[ti * 4 + ii][tj * 4 + jj] <= host_c[ii][jj];
      end
    end
  end
endmodule
