#!/usr/bin/env python3
"""Export a real GPT-2 layer0 mlp.c_fc GEMM tile for examples/gpt2_npu/.

Host runs full GPT-2; RTL only sees int8-quantized (sign-extended int32) A/B
and integer golden C. CTest uses committed artifacts (offline).
"""
from __future__ import annotations

import argparse
import json
import pathlib
from typing import Tuple

import numpy as np


def quant_sym_i8(x: np.ndarray) -> Tuple[np.ndarray, float]:
    x = np.asarray(x, dtype=np.float64)
    max_abs = float(np.max(np.abs(x))) if x.size else 0.0
    scale = max_abs / 127.0 if max_abs > 0 else 1.0
    q = np.rint(np.clip(x / scale, -127, 127)).astype(np.int32)
    return q, scale


def emit_init(name: str, M: np.ndarray) -> str:
    lines = []
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            v = int(M[i, j])
            # Unary-minus form so vs parse_number stays non-negative digits.
            if v < 0:
                lines.append(f"    {name}[{i}][{j}] = -32'd{-v};")
            else:
                lines.append(f"    {name}[{i}][{j}] = 32'd{v};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", type=pathlib.Path, default=pathlib.Path("examples/gpt2_npu"))
    ap.add_argument("--model", default="openai-community/gpt2")
    ap.add_argument("--prompt", default="Hello")
    ap.add_argument("--layer", type=int, default=0)
    ap.add_argument("--n", type=int, default=4)
    ap.add_argument("--k", type=int, default=32)
    ap.add_argument("--m", type=int, default=32)
    ap.add_argument("--row0", type=int, default=0)
    ap.add_argument("--k0", type=int, default=0)
    ap.add_argument("--m0", type=int, default=0)
    args = ap.parse_args()

    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tok = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(args.model)
    model.eval()

    ids = tok.encode(args.prompt, return_tensors="pt")
    captured = {}

    def hook(_mod, inp, _out):
        # c_fc: inp[0] is [batch, seq, n_embd]
        captured["x"] = inp[0].detach().cpu().numpy()

    handle = model.transformer.h[args.layer].mlp.c_fc.register_forward_hook(hook)
    with torch.no_grad():
        model(ids)
    handle.remove()

    if "x" not in captured:
        raise RuntimeError("hook did not capture c_fc input")

    # GPT-2 Conv1D weight: [n_embd, 4*n_embd]; forward is x @ weight + bias
    w = model.transformer.h[args.layer].mlp.c_fc.weight.detach().cpu().numpy()
    x = captured["x"]
    if x.ndim == 3:
        x = x[0]  # [seq, n_embd]

    n, k, m = args.n, args.k, args.m
    seq, d = x.shape
    assert w.shape[0] == d, f"W rows {w.shape[0]} != d {d}"

    x_pad = np.zeros((max(seq, args.row0 + n), d), dtype=np.float64)
    x_pad[:seq] = x

    a_f = x_pad[args.row0 : args.row0 + n, args.k0 : args.k0 + k]
    b_f = w[args.k0 : args.k0 + k, args.m0 : args.m0 + m]
    if a_f.shape != (n, k) or b_f.shape != (k, m):
        raise RuntimeError(f"slice shape mismatch A{a_f.shape} B{b_f.shape} want {(n,k)} {(k,m)}")

    a_q, s_a = quant_sym_i8(a_f)
    b_q, s_b = quant_sym_i8(b_f)
    c = (a_q.astype(np.int64) @ b_q.astype(np.int64)).astype(np.int32)

    out = args.out_dir
    out.mkdir(parents=True, exist_ok=True)

    a_init = emit_init("a", a_q)
    b_init = emit_init("b", b_q)

    # vs watch prints uint bit-pattern (not signed decimal).
    expect = [f"c_{i}_{j}={int(c[i, j]) & 0xFFFFFFFF}" for i in range(n) for j in range(m)]
    watch = ",".join(f"c_{i}_{j}" for i in range(n) for j in range(m))

    gemm_v = f"""// Auto-generated by tools/gpt2_npu/export_tile.py — do not edit by hand.
// GPT-2 {args.model} layer{args.layer} mlp.c_fc tile  N={n} K={k} M={m}
// Quant: symmetric int8, stored sign-extended in 32-bit regs; C = A·B (int32).
//
// @vs view matrix A array=a rows={n} cols={k}
// @vs view matrix B array=b rows={k} cols={m}
// @vs view matrix C array=c rows={n} cols={m}
// @vs op matmul out=C left=A right=B
module gpt2_npu_gemm_tile;
  reg  [31:0] a [0:{n - 1}][0:{k - 1}];
  reg  [31:0] b [0:{k - 1}][0:{m - 1}];
  wire [31:0] c [0:{n - 1}][0:{m - 1}];
  initial begin
{a_init}
{b_init}
  end
  blas_gemm #(.N({n}), .K({k}), .M({m}), .WA(32), .WB(32), .CW(32)) u (
    .a(a), .b(b), .c(c)
  );
endmodule
"""

    (out / "gemm_tile.v").write_text(gemm_v)
    (out / "a_init.inc").write_text(a_init + "\n")
    (out / "b_init.inc").write_text(b_init + "\n")
    (out / "expect_c.inc").write_text("\n".join(expect) + "\n")
    (out / "watch.txt").write_text(watch + "\n")

    meta = {
        "model": args.model,
        "prompt": args.prompt,
        "layer": args.layer,
        "op": "mlp.c_fc",
        "N": n,
        "K": k,
        "M": m,
        "row0": args.row0,
        "k0": args.k0,
        "m0": args.m0,
        "scale_a": s_a,
        "scale_b": s_b,
        "seq_len": int(seq),
        "n_embd": int(d),
        "A": a_q.tolist(),
        "B": b_q.tolist(),
        "C": c.tolist(),
        "note": "Full GPT-2 on host; RTL runs this int8 tile via blas_gemm (WA=32 sign-extended).",
    }
    (out / "golden.json").write_text(json.dumps(meta, indent=2) + "\n")

    readme = f"""# GPT-2 NPU GEMM tile

Host runs **full GPT-2** (`{args.model}`); this directory is one **real** `layer{args.layer}.mlp.c_fc` tile
(quantized int8 → int32 GEMM) for `vs` + `blas_gemm`.

| File | Role |
|------|------|
| `gemm_tile.v` | Combinational top (generated) |
| `expect_c.inc` / `watch.txt` | CTest |
| `golden.json` | Scales, offsets, full A/B/C |

Regenerate:

```bash
pip install -r tools/gpt2_npu/requirements.txt
python3 tools/gpt2_npu/export_tile.py --out-dir examples/gpt2_npu
```

Run:

```bash
./build/vs run examples/gpt2_npu/gemm_tile.v examples/blas/gemm.v \\
  --threads 1 --until 40 --watch "$(cat examples/gpt2_npu/watch.txt)"
```

Default tile: N={n} K={k} M={m} (kept modest for sim pending limits).
"""
    (out / "README.md").write_text(readme)
    print(f"wrote {out}  C[0][:4]={c[0, :4].tolist()}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
