#!/usr/bin/env python3
"""Generate examples/tiny_npu/weights.v + golden.json matching RTL hard-attn forward."""
from __future__ import annotations

import argparse
import json
import pathlib
import random
import sys

T, D, HF, WBITS = 4, 4, 8, 8
SEED = 20260918


def mat(rng: random.Random, rows: int, cols: int, lo: int = 0, hi: int = 7):
    return [[rng.randint(lo, hi) for _ in range(cols)] for _ in range(rows)]


def gemm(A, B):
    n, k, m = len(A), len(A[0]), len(B[0])
    C = [[0] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            s = 0
            for kk in range(k):
                s += A[i][kk] * B[kk][j]
            C[i][j] = s
    return C


def gemm_bt(A, B):
    n, k, m = len(A), len(A[0]), len(B)
    C = [[0] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            s = 0
            for kk in range(k):
                s += A[i][kk] * B[j][kk]
            C[i][j] = s
    return C


def row_argmax_onehot(S):
    t = len(S)
    A = [[0] * t for _ in range(t)]
    for i in range(t):
        best_j, best = 0, S[i][0]
        for j in range(1, t):
            if S[i][j] > best:
                best, best_j = S[i][j], j
        A[i][best_j] = 1
    return A


def relu32(X):
    out = []
    for row in X:
        out.append([0 if (v & 0x80000000) else int(v & 0xFFFFFFFF) for v in row])
    return out


def emit_initial(name: str, M, w: int = 8) -> str:
    lines = []
    for i, row in enumerate(M):
        for j, v in enumerate(row):
            lines.append(f"    {name}[{i}][{j}] = {w}'d{v};")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", type=pathlib.Path, default=pathlib.Path("examples/tiny_npu"))
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    X = mat(rng, T, D, 1, 5)
    Wq, Wk, Wv = mat(rng, D, D), mat(rng, D, D), mat(rng, D, D)
    W1, W2 = mat(rng, D, HF), mat(rng, HF, D)

    Q, K, V = gemm(X, Wq), gemm(X, Wk), gemm(X, Wv)
    S = gemm_bt(Q, K)
    A = row_argmax_onehot(S)
    O = gemm(A, V)
    H = relu32(gemm(O, W1))
    Y = gemm(H, W2)

    out = args.out_dir
    out.mkdir(parents=True, exist_ok=True)

    def emit_demo_init(name: str, M) -> str:
        return "\n".join(
            f"    {name}[{i}][{j}] = 8'd{v};"
            for i, row in enumerate(M)
            for j, v in enumerate(row)
        )

    weights_v = f"""// Auto-generated by tools/tiny_npu/gen_model.py — do not edit by hand.
// Seed={args.seed}  T={T} D={D} HF={HF}  unsigned {WBITS}-bit (toy quantized).
module tiny_npu_weights (
  output reg [7:0] wq [0:3][0:3],
  output reg [7:0] wk [0:3][0:3],
  output reg [7:0] wv [0:3][0:3],
  output reg [7:0] w1 [0:3][0:7],
  output reg [7:0] w2 [0:7][0:3]
);
  initial begin
{emit_initial("wq", Wq)}
{emit_initial("wk", Wk)}
{emit_initial("wv", Wv)}
{emit_initial("w1", W1)}
{emit_initial("w2", W2)}
  end
endmodule
"""
    (out / "weights.v").write_text(weights_v)

    forces = [f"x_{i}_{j}={X[i][j]}" for i in range(T) for j in range(D)]
    force_cli = [f"--force {f}" for f in forces]
    expect_y = [f"y_{i}_{j}={Y[i][j]}" for i in range(T) for j in range(D)]
    expect_gemm = [f"c_{i}_{j}={Q[i][j]}" for i in range(T) for j in range(D)]
    expect_attn = [f"o_{i}_{j}={O[i][j]}" for i in range(T) for j in range(D)]
    expect_mlp = [f"y_{i}_{j}={Y[i][j]}" for i in range(T) for j in range(D)]

    # Split demos: GEMM = X·Wq; MLP = full FFN path inputs fixed to O/W*; ATTN = hard-attn slice
    demo_gemm = f"""// Auto-generated: GEMM X·Wq → Q
// @vs view matrix A array=a rows=4 cols=4
// @vs view matrix B array=b rows=4 cols=4
// @vs view matrix C array=c rows=4 cols=4
// @vs op matmul out=C left=A right=B
module demo_gemm;
  reg  [7:0]  a [0:3][0:3];
  reg  [7:0]  b [0:3][0:3];
  wire [31:0] c [0:3][0:3];
  initial begin
{emit_demo_init("a", X)}
{emit_demo_init("b", Wq)}
  end
  blas_gemm #(.N(4), .K(4), .M(4), .WA(8), .WB(8), .CW(32)) u (
    .a(a), .b(b), .c(c)
  );
endmodule
"""
    demo_attn = f"""// Auto-generated: hard attention O = onehot(argmax(Q·Kᵀ)) · V
// @vs view matrix Q array=q rows=4 cols=4
// @vs view matrix K array=k rows=4 cols=4
// @vs view matrix V array=v rows=4 cols=4
// @vs view matrix S array=s rows=4 cols=4
// @vs view matrix A array=a rows=4 cols=4
// @vs view matrix O array=o rows=4 cols=4
module demo_attn;
  reg  [31:0] q [0:3][0:3];
  reg  [31:0] k [0:3][0:3];
  reg  [31:0] v [0:3][0:3];
  wire [31:0] s [0:3][0:3];
  wire [31:0] a [0:3][0:3];
  wire [31:0] o [0:3][0:3];
  initial begin
{emit_demo_init("q", Q).replace("8'd", "32'd")}
{emit_demo_init("k", K).replace("8'd", "32'd")}
{emit_demo_init("v", V).replace("8'd", "32'd")}
  end
  blas_gemm_bt #(.N(4), .K(4), .M(4), .WA(32), .WB(32), .CW(32)) u_s (
    .a(q), .b(k), .c(s)
  );
  blas_row_argmax #(.T(4), .W(32)) u_a (
    .s(s), .a(a)
  );
  blas_gemm #(.N(4), .K(4), .M(4), .WA(32), .WB(32), .CW(32)) u_o (
    .a(a), .b(v), .c(o)
  );
endmodule
"""
    demo_mlp = f"""// Auto-generated: FFN Y = ReLU(O·W1)·W2
// @vs view matrix O array=o rows=4 cols=4
// @vs view matrix H array=h rows=4 cols=8
// @vs view matrix Y array=y rows=4 cols=4
module demo_mlp;
  reg  [31:0] o [0:3][0:3];
  reg  [7:0]  w1 [0:3][0:7];
  reg  [7:0]  w2 [0:7][0:3];
  wire [31:0] h_pre [0:3][0:7];
  wire [31:0] h [0:3][0:7];
  wire [31:0] y [0:3][0:3];
  initial begin
{emit_demo_init("o", O).replace("8'd", "32'd")}
{emit_demo_init("w1", W1)}
{emit_demo_init("w2", W2)}
  end
  blas_gemm #(.N(4), .K(4), .M(8), .WA(32), .WB(8), .CW(32)) u_h (
    .a(o), .b(w1), .c(h_pre)
  );
  blas_relu #(.N(4), .M(8), .W(32)) u_relu (
    .x(h_pre), .y(h)
  );
  blas_gemm #(.N(4), .K(8), .M(4), .WA(32), .WB(8), .CW(32)) u_y (
    .a(h), .b(w2), .c(y)
  );
endmodule
"""
    (out / "demo_gemm.v").write_text(demo_gemm)
    (out / "demo_attn.v").write_text(demo_attn)
    (out / "demo_mlp.v").write_text(demo_mlp)

    meta = {
        "seed": args.seed,
        "T": T,
        "D": D,
        "HF": HF,
        "X": X,
        "Wq": Wq,
        "Wk": Wk,
        "Wv": Wv,
        "W1": W1,
        "W2": W2,
        "Q": Q,
        "K": K,
        "V": V,
        "S": S,
        "A": A,
        "O": O,
        "H": H,
        "Y": Y,
        "forces": force_cli,
        "watch": ",".join(f"y_{i}_{j}" for i in range(T) for j in range(D)),
        "expect": expect_y,
    }
    (out / "golden.json").write_text(json.dumps(meta, indent=2) + "\n")
    (out / "forces.txt").write_text("\n".join(forces) + "\n")
    (out / "expect_y.inc").write_text("\n".join(["done=1"] + expect_y) + "\n")
    (out / "expect_gemm.inc").write_text("\n".join(expect_gemm) + "\n")
    (out / "expect_attn.inc").write_text("\n".join(expect_attn) + "\n")
    (out / "expect_mlp.inc").write_text("\n".join(expect_mlp) + "\n")
    print(f"wrote {out}  Y[0]={Y[0]}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
