#!/usr/bin/env python3
"""Generate tiled GEMM — full-tile parallel host bus (1 beat = whole T×T).

  LOAD:  1 cycle writes all A[i][j] and B[i][j] in parallel (2·T² NBAs)
  STORE: 1 cycle reads all C tile elements in parallel

Dominant cycles ≈ NT³ · 4  (+ CLEAR/STORE per C tile)
  M=1024, T=32 → ≈ 1.3×10⁵ cycles ≈ 1.3 ms @ 100 MHz
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "examples" / "fpga_gemm3"


def emit_ctrl(m: int, t: int) -> str:
    nt = m // t
    assert m == nt * t
    mod = f"gemm{m}_tiled_ctrl"
    return "\n".join(
        [
            f"// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.",
            f"// Tiled GEMM (full-tile parallel bus): M={m}, T={t}, NT={nt}, leaves={nt**3}",
            f"// LOAD=1 beat (parallel A||B), STORE=1 beat (parallel C). Leaf mac still 1-cycle latch.",
            f"module {mod} (",
            f"  input  wire clk,",
            f"  input  wire rst,",
            f"  input  wire start,",
            f"  input  wire          host_we,",
            f"  input  wire [7:0]    host_a [0:{t - 1}][0:{t - 1}],",
            f"  input  wire [7:0]    host_b [0:{t - 1}][0:{t - 1}],",
            f"  input  wire          host_re,",
            f"  output reg  [31:0]   host_c [0:{t - 1}][0:{t - 1}],",
            f"  output reg           done,",
            f"  output reg  [3:0]    phase,",
            f"  output reg  [7:0]    ti,",
            f"  output reg  [7:0]    tj,",
            f"  output reg  [7:0]    tk,",
            f"  output reg  [7:0]    a_mem [0:{t - 1}][0:{t - 1}],",
            f"  output reg  [7:0]    b_mem [0:{t - 1}][0:{t - 1}],",
            f"  input  wire [31:0]   c_comb [0:{t - 1}][0:{t - 1}]",
            f");",
            f"  reg [31:0] prod [0:{t - 1}][0:{t - 1}];",
            f"  reg [31:0] acc [0:{t - 1}][0:{t - 1}];",
            f"  integer ii, jj;",
            f"  reg started;",
            f"",
            f"  // 0 IDLE 1 CLEAR 2 LOAD 3 LATCH 4 ACCUM 5 ADV 6 STORE 7 FIN",
            f"  always @(posedge clk) begin",
            f"    if (rst) begin",
            f"      done <= 1'b0; phase <= 4'd0; started <= 1'b0;",
            f"      ti <= 8'd0; tj <= 8'd0; tk <= 8'd0;",
            f"      for (ii = 0; ii < {t}; ii = ii + 1)",
            f"        for (jj = 0; jj < {t}; jj = jj + 1) begin",
            f"          a_mem[ii][jj] <= 8'd0; b_mem[ii][jj] <= 8'd0;",
            f"          prod[ii][jj] <= 32'd0; acc[ii][jj] <= 32'd0;",
            f"          host_c[ii][jj] <= 32'd0;",
            f"        end",
            f"    end else if (phase == 4'd0) begin",
            f"      if (start && !started) begin",
            f"        done <= 1'b0; started <= 1'b1;",
            f"        ti <= 8'd0; tj <= 8'd0; tk <= 8'd0;",
            f"        phase <= 4'd1;",
            f"      end",
            f"    end else if (phase == 4'd1) begin",
            f"      for (ii = 0; ii < {t}; ii = ii + 1)",
            f"        for (jj = 0; jj < {t}; jj = jj + 1)",
            f"          acc[ii][jj] <= 32'd0;",
            f"      phase <= 4'd2;",
            f"    end else if (phase == 4'd2) begin",
            f"      // 1 beat: parallel write entire A and B tiles (2·T² ports)",
            f"      if (host_we) begin",
            f"        for (ii = 0; ii < {t}; ii = ii + 1)",
            f"          for (jj = 0; jj < {t}; jj = jj + 1) begin",
            f"            a_mem[ii][jj] <= host_a[ii][jj];",
            f"            b_mem[ii][jj] <= host_b[ii][jj];",
            f"          end",
            f"      end",
            f"      phase <= 4'd3;",
            f"    end else if (phase == 4'd3) begin",
            f"      for (ii = 0; ii < {t}; ii = ii + 1)",
            f"        for (jj = 0; jj < {t}; jj = jj + 1)",
            f"          prod[ii][jj] <= c_comb[ii][jj];",
            f"      phase <= 4'd4;",
            f"    end else if (phase == 4'd4) begin",
            f"      for (ii = 0; ii < {t}; ii = ii + 1)",
            f"        for (jj = 0; jj < {t}; jj = jj + 1)",
            f"          acc[ii][jj] <= acc[ii][jj] + prod[ii][jj];",
            f"      phase <= 4'd5;",
            f"    end else if (phase == 4'd5) begin",
            f"      if (tk + 8'd1 >= 8'd{nt}) begin",
            f"        for (ii = 0; ii < {t}; ii = ii + 1)",
            f"          for (jj = 0; jj < {t}; jj = jj + 1)",
            f"            host_c[ii][jj] <= acc[ii][jj];",
            f"        phase <= 4'd6;",
            f"      end else begin",
            f"        tk <= tk + 8'd1;",
            f"        phase <= 4'd2;",
            f"      end",
            f"    end else if (phase == 4'd6) begin",
            f"      // 1 beat: host samples parallel host_c",
            f"      if (host_re) begin",
            f"        tk <= 8'd0;",
            f"        if (tj + 8'd1 >= 8'd{nt}) begin",
            f"          if (ti + 8'd1 >= 8'd{nt}) phase <= 4'd7;",
            f"          else begin ti <= ti + 8'd1; tj <= 8'd0; phase <= 4'd1; end",
            f"        end else begin",
            f"          tj <= tj + 8'd1; phase <= 4'd1;",
            f"        end",
            f"      end",
            f"    end else if (phase == 4'd7) begin",
            f"      done <= 1'b1; started <= 1'b0; phase <= 4'd0;",
            f"    end",
            f"  end",
            f"endmodule",
            f"",
        ]
    )


def emit_top(m: int, t: int) -> str:
    mac = f"gemm{t}_mac_array"
    ctrl = f"gemm{m}_tiled_ctrl"
    mod = f"gemm{m}_tiled_top"
    return "\n".join(
        [
            f"// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.",
            f"module {mod} (",
            f"  input  wire clk,",
            f"  input  wire rst,",
            f"  input  wire start,",
            f"  input  wire          host_we,",
            f"  input  wire [7:0]    host_a [0:{t - 1}][0:{t - 1}],",
            f"  input  wire [7:0]    host_b [0:{t - 1}][0:{t - 1}],",
            f"  input  wire          host_re,",
            f"  output wire [31:0]   host_c [0:{t - 1}][0:{t - 1}],",
            f"  output wire          done,",
            f"  output wire [3:0]    phase,",
            f"  output wire [7:0]    ti,",
            f"  output wire [7:0]    tj,",
            f"  output wire [7:0]    tk",
            f");",
            f"  wire [7:0]  a_mem [0:{t - 1}][0:{t - 1}];",
            f"  wire [7:0]  b_mem [0:{t - 1}][0:{t - 1}];",
            f"  wire [31:0] c_comb [0:{t - 1}][0:{t - 1}];",
            f"",
            f"  {mac} u_mac (.a(a_mem), .b(b_mem), .c(c_comb));",
            f"",
            f"  {ctrl} u_ctrl (",
            f"    .clk(clk), .rst(rst), .start(start),",
            f"    .host_we(host_we), .host_a(host_a), .host_b(host_b),",
            f"    .host_re(host_re), .host_c(host_c),",
            f"    .done(done), .phase(phase), .ti(ti), .tj(tj), .tk(tk),",
            f"    .a_mem(a_mem), .b_mem(b_mem), .c_comb(c_comb)",
            f"  );",
            f"endmodule",
            f"",
        ]
    )


def emit_demo(m: int, t: int) -> str:
    """A=I, B=1..M² → C=B; tiles extracted in parallel from full matrices."""
    nt = m // t
    mac = f"gemm{t}_mac_array"
    ctrl = f"gemm{m}_tiled_ctrl"
    mod = f"gemm{m}_tiled_demo"
    lines = [
        f"// Auto-generated by tools/fpga_gemm3/gen_tiled.py — do not edit by hand.",
        f"// Demo M={m} T={t}: full-tile parallel LOAD/STORE; A=I, B=1..{m*m} → C=B",
        f"// @vs view matrix C array=c rows={m} cols={m}",
        f"module {mod} (",
        f"  input  wire clk,",
        f"  input  wire rst,",
        f"  output wire done,",
        f"  output wire [3:0] phase,",
        f"  output wire [31:0] c [0:{m - 1}][0:{m - 1}]",
        f");",
        f"  reg start, kicked;",
        f"  wire host_we, host_re;",
        f"  wire [7:0] ti, tj, tk;",
        f"  reg  [7:0]  a_full [0:{m - 1}][0:{m - 1}];",
        f"  reg  [7:0]  b_full [0:{m - 1}][0:{m - 1}];",
        f"  reg  [7:0]  host_a [0:{t - 1}][0:{t - 1}];",
        f"  reg  [7:0]  host_b [0:{t - 1}][0:{t - 1}];",
        f"  wire [31:0] host_c [0:{t - 1}][0:{t - 1}];",
        f"  wire [7:0]  a_mem [0:{t - 1}][0:{t - 1}];",
        f"  wire [7:0]  b_mem [0:{t - 1}][0:{t - 1}];",
        f"  wire [31:0] c_comb [0:{t - 1}][0:{t - 1}];",
        f"  reg  [31:0] c_full [0:{m - 1}][0:{m - 1}];",
        f"  integer ri, cj, ii, jj;",
        f"",
        f"  {mac} u_mac (.a(a_mem), .b(b_mem), .c(c_comb));",
        f"",
        f"  {ctrl} u_ctrl (",
        f"    .clk(clk), .rst(rst), .start(start),",
        f"    .host_we(host_we), .host_a(host_a), .host_b(host_b),",
        f"    .host_re(host_re), .host_c(host_c),",
        f"    .done(done), .phase(phase), .ti(ti), .tj(tj), .tk(tk),",
        f"    .a_mem(a_mem), .b_mem(b_mem), .c_comb(c_comb)",
        f"  );",
        f"",
        f"  assign host_we = (phase == 4'd2);",
        f"  assign host_re = (phase == 4'd6);",
        f"",
    ]
    for i in range(m):
        for j in range(m):
            lines.append(f"  assign c[{i}][{j}] = c_full[{i}][{j}];")

    lines += [
        f"",
        f"  // Parallel tile extract from full A/B (T² reads each beat)",
        f"  always @* begin",
        f"    for (ii = 0; ii < {t}; ii = ii + 1)",
        f"      for (jj = 0; jj < {t}; jj = jj + 1) begin",
        f"        host_a[ii][jj] = a_full[ti * {t} + ii][tk * {t} + jj];",
        f"        host_b[ii][jj] = b_full[tk * {t} + ii][tj * {t} + jj];",
        f"      end",
        f"  end",
        f"",
        f"  initial begin",
        f"    for (ri = 0; ri < {m}; ri = ri + 1)",
        f"      for (cj = 0; cj < {m}; cj = cj + 1) begin",
        f"        if (ri == cj) a_full[ri][cj] = 8'd1;",
        f"        else          a_full[ri][cj] = 8'd0;",
        f"        b_full[ri][cj] = ri * {m} + cj + 1;",
        f"      end",
        f"  end",
        f"",
        f"  always @(posedge clk) begin",
        f"    if (rst) begin",
        f"      start <= 1'b0; kicked <= 1'b0;",
        f"      for (ri = 0; ri < {m}; ri = ri + 1)",
        f"        for (cj = 0; cj < {m}; cj = cj + 1)",
        f"          c_full[ri][cj] <= 32'd0;",
        f"    end else begin",
        f"      start <= 1'b0;",
        f"      if (!kicked) begin start <= 1'b1; kicked <= 1'b1; end",
        f"      // 1 beat: parallel write-back of whole C tile",
        f"      if (phase == 4'd6) begin",
        f"        for (ii = 0; ii < {t}; ii = ii + 1)",
        f"          for (jj = 0; jj < {t}; jj = jj + 1)",
        f"            c_full[ti * {t} + ii][tj * {t} + jj] <= host_c[ii][jj];",
        f"      end",
        f"    end",
        f"  end",
        f"endmodule",
        f"",
    ]
    return "\n".join(lines)


def emit_doc(m: int, t: int) -> str:
    nt = m // t
    # per C-tile: CLEAR1 + NT*(LOAD1+LATCH1+ACCUM1+ADV1) + STORE1 = 1+4*NT+1
    n_cyc = nt * nt * (2 + 4 * nt)
    t_100_ms = n_cyc / 1e8 * 1e3
    return "\n".join(
        [
            f"# {m}×{m} @ tile {t}（整 tile 并行总线）",
            "",
            f"| 项 | 值 |",
            f"|----|---:|",
            f"| NT | {nt} |",
            f"| 叶次数 | {nt**3} |",
            f"| LOAD | **1 拍**（并行写满 A‖B，共 2·{t}² 路） |",
            f"| STORE | **1 拍**（并行读出 C tile） |",
            f"| 约总拍数 | {n_cyc} |",
            f"| @100 MHz | ≈ **{t_100_ms:.2f} ms** |",
            "",
            f"详见 [README.md](README.md)。",
            "",
        ]
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--matrix", type=int, default=1024)
    ap.add_argument("--tile", type=int, default=32)
    ap.add_argument("--demo", action="store_true")
    ap.add_argument("--out-dir", type=Path, default=ROOT)
    args = ap.parse_args()
    m, t = args.matrix, args.tile
    if m % t:
        raise SystemExit("matrix % tile != 0")
    if t not in (2, 4, 8, 16, 32):
        raise SystemExit("tile must be 2/4/8/16/32")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / f"gemm{m}_tiled_ctrl.v").write_text(emit_ctrl(m, t))
    (args.out_dir / f"gemm{m}_tiled_top.v").write_text(emit_top(m, t))
    (args.out_dir / f"gemm{m}_decomp.md").write_text(emit_doc(m, t))
    print(f"wrote gemm{m} (full-tile parallel bus), N_cyc≈{ (m//t)**2 * (2 + 4*(m//t)) }")

    if args.demo:
        if m > 16:
            raise SystemExit("--demo requires matrix<=16")
        (args.out_dir / f"gemm{m}_tiled_demo.v").write_text(emit_demo(m, t))
        print(f"wrote gemm{m}_tiled_demo.v")


if __name__ == "__main__":
    main()
