#!/usr/bin/env python3
"""Generate structural N×N×N multiplier-cluster RTL (vs has no generate).

Each product is an explicit `assign` (= one multiplier).
Module / file name: gemm{N}_mac_array
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "examples" / "fpga_gemm3"
DEFAULT_NS = (2, 4, 8, 16, 32)


def emit(n: int, wa: int = 8, wb: int = 8, cw: int = 32) -> str:
    mod = f"gemm{n}_mac_array"
    lines: list[str] = []
    lines.append("// Auto-generated by tools/fpga_gemm3/gen_mac_array.py — do not edit by hand.")
    lines.append(f"// Fixed multiplier cluster: C = A·B, N={n}")
    lines.append(f"//   {n**3} multipliers + {n * n} N-input sums; pure combo; 1 cycle latch outside.")
    lines.append("//")
    lines.append(f"// @vs view matrix A array=a rows={n} cols={n}")
    lines.append(f"// @vs view matrix B array=b rows={n} cols={n}")
    lines.append(f"// @vs view matrix C array=c rows={n} cols={n}")
    lines.append(f"// @vs op matmul out=C left=A right=B")
    lines.append(f"module {mod} (")
    lines.append(f"  input  wire [{wa - 1}:0] a [0:{n - 1}][0:{n - 1}],")
    lines.append(f"  input  wire [{wb - 1}:0] b [0:{n - 1}][0:{n - 1}],")
    lines.append(f"  output wire [{cw - 1}:0] c [0:{n - 1}][0:{n - 1}]")
    lines.append(");")
    lines.append(f"  // ---- {n**3} multipliers: mul_i_j_k = A[i][k] * B[k][j] ----")
    for i in range(n):
        for j in range(n):
            for k in range(n):
                lines.append(f"  wire [{cw - 1}:0] mul_{i}_{j}_{k};")
                lines.append(
                    f"  assign mul_{i}_{j}_{k} = a[{i}][{k}] * b[{k}][{j}];"
                )
    lines.append(f"  // ---- {n * n} reductions: C[i][j] = Σ_k mul_i_j_k ----")
    for i in range(n):
        for j in range(n):
            terms = " + ".join(f"mul_{i}_{j}_{k}" for k in range(n))
            lines.append(f"  assign c[{i}][{j}] = {terms};")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def write_one(n: int, out_dir: Path) -> Path:
    path = out_dir / f"gemm{n}_mac_array.v"
    path.write_text(emit(n))
    print(f"wrote {path}  (N={n}, muls={n**3})")
    return path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, action="append", help="matrix size (repeatable)")
    ap.add_argument(
        "--all",
        action="store_true",
        help=f"generate N in {DEFAULT_NS}",
    )
    ap.add_argument(
        "-o",
        type=Path,
        default=None,
        help="output file (only with single --n)",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT,
        help="directory for gemm{N}_mac_array.v",
    )
    args = ap.parse_args()
    ns = list(args.n) if args.n else ([] if not args.all else list(DEFAULT_NS))
    if not ns:
        ns = list(DEFAULT_NS)

    for n in ns:
        if not (1 <= n <= 32):
            raise SystemExit(f"N={n} out of range 1..32")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    if args.o is not None:
        if len(ns) != 1:
            raise SystemExit("-o requires exactly one --n")
        args.o.parent.mkdir(parents=True, exist_ok=True)
        args.o.write_text(emit(ns[0]))
        print(f"wrote {args.o}  (N={ns[0]}, muls={ns[0]**3})")
        return

    for n in ns:
        write_one(n, args.out_dir)


if __name__ == "__main__":
    main()
